repos:
  - repo: local
    hooks:
      - id: deno-fmt
        name: deno fmt
        entry: deno fmt
        language: system
        types: [file]
        files: '\.ts$'
      - id: deno-lint
        name: deno lint
        entry: deno lint --unstable
        language: system
        types: [file, ts]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.1
    hooks:
      - id: codespell
        entry: codespell --ignore-words=.codespell_ignore --quiet-level=4 --check-filenames
        exclude: \.(csv|json|txt)$
