name: hooks
on:
  release:
    types:
      - created
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.4.2
      - uses: actions/setup-node@v3
        with:
          node-version: v24.4.1
          registry-url: "https://registry.npmjs.org"
      - run: deno task build ${GITHUB_REF#refs/*/}
      - run: npm publish
        working-directory: dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
